# Generated by Django 3.2.8 on 2023-02-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KalimpioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_monitored', models.DateField()),
                ('dealer', models.CharField(max_length=50)),
                ('pickup', models.CharField(max_length=50)),
                ('rnd', models.IntegerField(default=0)),
                ('square', models.CharField(max_length=50)),
                ('squareSmall', models.CharField(max_length=50)),
                ('small', models.CharField(max_length=50)),
                ('dayparts', models.TextField(blank=True)),
                ('suspicious', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LabangonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_monitored', models.DateField()),
                ('dealer', models.CharField(max_length=50)),
                ('pickup', models.CharField(max_length=50)),
                ('rnd', models.IntegerField(default=0)),
                ('square', models.CharField(max_length=50)),
                ('squareSmall', models.CharField(max_length=50)),
                ('small', models.CharField(max_length=50)),
                ('dayparts', models.TextField(blank=True)),
                ('suspicious', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TalambanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_monitored', models.DateField()),
                ('dealer', models.CharField(max_length=50)),
                ('pickup', models.CharField(max_length=50)),
                ('rnd', models.IntegerField(default=0)),
                ('square', models.CharField(max_length=50)),
                ('squareSmall', models.CharField(max_length=50)),
                ('small', models.CharField(max_length=50)),
                ('dayparts', models.TextField(blank=True)),
                ('suspicious', models.TextField()),
            ],
        ),
    ]
