# Generated by Django 3.2.8 on 2023-02-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busyCctvCounter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kalimpiomodel',
            name='cctvTime',
            field=models.CharField(default='07:00 AM', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labangonmodel',
            name='cctvTime',
            field=models.CharField(default='07:00 AM', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='talambanmodel',
            name='cctvTime',
            field=models.CharField(default='07:00 AM', max_length=50),
            preserve_default=False,
        ),
    ]
