# Generated by Django 3.2.8 on 2023-02-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busyCctvCounter', '0002_auto_20230225_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kalimpiomodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='labangonmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='talambanmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
