# Generated by Django 3.2.8 on 2023-02-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busyCctvCounter', '0003_auto_20230225_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kalimpiomodel',
            name='cctvTime',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='kalimpiomodel',
            name='date_monitored',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kalimpiomodel',
            name='dayparts',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kalimpiomodel',
            name='dealer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='kalimpiomodel',
            name='pickup',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='kalimpiomodel',
            name='rnd',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='kalimpiomodel',
            name='small',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='kalimpiomodel',
            name='square',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='kalimpiomodel',
            name='squareSmall',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='kalimpiomodel',
            name='suspicious',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='labangonmodel',
            name='cctvTime',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='labangonmodel',
            name='date_monitored',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='labangonmodel',
            name='dayparts',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='labangonmodel',
            name='dealer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='labangonmodel',
            name='pickup',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='labangonmodel',
            name='rnd',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='labangonmodel',
            name='small',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='labangonmodel',
            name='square',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='labangonmodel',
            name='squareSmall',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='labangonmodel',
            name='suspicious',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='talambanmodel',
            name='cctvTime',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='talambanmodel',
            name='date_monitored',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='talambanmodel',
            name='dayparts',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='talambanmodel',
            name='dealer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='talambanmodel',
            name='pickup',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='talambanmodel',
            name='rnd',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='talambanmodel',
            name='small',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='talambanmodel',
            name='square',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='talambanmodel',
            name='squareSmall',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='talambanmodel',
            name='suspicious',
            field=models.TextField(blank=True, null=True),
        ),
    ]
