# Generated by Django 4.2 on 2023-04-28 09:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('busyCctvCounter', '0004_auto_20230225_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kalimpiomodel',
            name='id',
        ),
        migrations.RemoveField(
            model_name='labangonmodel',
            name='id',
        ),
        migrations.RemoveField(
            model_name='talambanmodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='kalimpiomodel',
            name='date_monitored',
            field=models.DateField(default=django.utils.timezone.now, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='labangonmodel',
            name='date_monitored',
            field=models.DateField(default=django.utils.timezone.now, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='talambanmodel',
            name='date_monitored',
            field=models.DateField(default=django.utils.timezone.now, primary_key=True, serialize=False),
        ),
    ]
